---
title: "Plot Error Decomposition"
output: html
editor_options: 
  chunk_output_type: console
---

Set up: import libraries and set seed.

```{r setup, include=FALSE}
source("R/phylo-inference-ml.R")
set.seed(113)
```

Generate synthetic data.

```{r}
n <- 1500 # number of observations
x <- runif(n, 0, 1) # true values
x_centered <- x - 0.5
y <- 0.7 * x + rnorm(n, 0.05, 0.1) # predicted values 
y_centered <- y - 0.5
lm <- lm(y_centered ~ x_centered)
```


Plot the figure.

```{r cars}

pdf("figures/fig-error-decomp.pdf", width=6*1.1, height=6)

plot(0 ,0 ,cex = .5, col = "grey65", xlab = "", ylab = "",
     xlim = c(-0.8, 0.8), ylim = c(-.8, 0.8))

abline(h=0, lw = 2, col = "black", lty = 3) # 0:1
abline(v=0, lw = 2, col = "black", lty = 3) # 1:0

# Plot data.
points(x_centered, y_centered,
  xlab = "", ylab = "", cex = .5, col = "grey65",
  xlim = c(-0.8, 0.8), ylim = c(-.8, 0.8)
)

# Plot lines.
abline(0, 1, lw = 2) # 1:1 line
abline(- 0.1 + 0.12, 0.7, lw = 2, lty = 4, col = "grey40") # variance - upper
abline(- 0.1 - 0.12, 0.7, lw = 2, lty = 4, col = "grey40") # variance - lower
abline(lm, lw = 2, lty = 2) # linear fit
# abline(v = 0, lty = 4, col = "grey", lw = 2) # y = 0

# Axis label.
title(xlab = "True (mean centered)", cex.lab = 1.5)
title(ylab = "Predicted", cex.lab = 1.5, line = 2.5)

# Set legend.
legend("topleft",
  legend = c("Data", "Linear fit", "1:1"),
  lty = c(NA, 2, 1), lw = c(NA, 2, 2), pch = c(1, NA, NA),
  col = c("grey40", "black", "black"), cex = 1.1
)
# Draw arrows.
arrows(0, 0.7 * 0.5 - 0.5 + 0.05, 0, 0, code = 3, length = .1, lw = 2) # uni
arrows(-0.40, -0.49, -0.47, -0.32, code = 3, length = .1, lw = 2) # var
iArrows <- igraph:::igraph.Arrows
iArrows(0.45, 0.21, 0.45, 0.45,
  h.lwd = 2, sh.lwd = 2, sh.col = "black",
  curve = 1 - 1.6 * ((1:10) %% 2), width = 1.1, size = .9
)
iArrows(0.45, 0.45, 0.45, .21,
  h.lwd = 2, sh.lwd = 2, sh.col = "black",
  curve = -1 + 1.6 * ((1:10) %% 2), width = 1.1, size = .9
)

# Add text for arrows. 
legend(
  x = -.42, y = -.53, "Variance", box.col = "white", bg = "white",
  cex = 1.3, x.intersp = -0.7, y.intersp = -0.2
)
legend(
  x = -0.16, y = 0.3, "Uniform", box.col = "white", bg = "white",
  cex = 1.3, x.intersp = -0.7, y.intersp = -0.2
)
legend(
  x = -0.10, y = 0.2, "bias", box.col = "white", bg = "white",
  cex = 1.3, x.intersp = -0.7, y.intersp = -0.2
)
legend(
  x = .39, y = .55, "Consistency", box.col = "white", bg = "white",
  cex = 1.3, x.intersp = -0.7, y.intersp = -0.2
)
legend(
  x = .52, y = .44, "bias", box.col = "white", bg = "white",
  cex = 1.3, x.intersp = -0.7, y.intersp = -0.2
)

dev.off()
```