---
title: "Error Decomposition"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(latex2exp)
library(igraph)
```

## Systematic error

```{r cars}
pdf("fig-error-decomp.pdf", width=6*1.1, height=6)
x  <- runif(1500,0,1)
y  <- .7*x + rnorm(1500,0.,.1)
lm <- lm(y ~ x)
plot(x, y, xlab = "", ylab = "", cex = .5, col = "grey45",
     xlim = c(-.3,1.3), ylim = c(-.3,1.3))
title(xlab = "True"     , cex.lab = 1.5)
title(ylab = "Predicted", cex.lab = 1.5, line = 2.5)
abline(0, 1, lw = 2)
abline(lm,   lw = 2, lty = 2)
abline(v=.5, lty = 4, col = "grey", lw = 2)
legend("topleft", legend = c("Data", "Linear fit","1:1"), 
       lty = c(NA,2,1), lw = c(NA,2,2), pch = c(1,NA,NA),
       col = c("grey40", "black", "black"), cex = 1.1)
legend(x = .38, y = -.2 , "<True>",  box.col = "white", bg = "white",
       cex = 1.1, x.intersp=-0.7, y.intersp=-0.2, text.col = "grey")
arrows(0.5, 0.7*0.5, 0.5, 0.5, code = 3, length = .1, lw = 2)
arrows(0., 0.0, 0., 0.2, code = 3, length = .1, lw = 2)
text(x = -.17, y = .1, "Variance", cex = 1.3)
text(x = .22  , y = .7, "Uniform" , cex = 1.3, adj = 0)
text(x = .28  , y = .59, "bias"    , cex = 1.3, adj = 0)
legend(x = .90, y = 1.13 , "Consistency",  box.col = "white", bg = "white",
       cex = 1.3, x.intersp=-0.7, y.intersp=-0.2)
legend(x = 1.06, y = .98 , "bias",  box.col = "white", bg = "white",
       cex = 1.3, x.intersp=-0.7, y.intersp=-0.2)
iArrows <- igraph:::igraph.Arrows
iArrows(1., .7, 1., 1.,
        h.lwd=2, sh.lwd=2, sh.col="black",
        curve=1 - 1.6*((1:8) %% 2), width=1.1, size=.9)
iArrows(1., 1., 1., .7,
        h.lwd=2, sh.lwd=2, sh.col="black",
        curve= -1 + 1.6*((1:8) %% 2), width=1.1, size=.9)
dev.off()
```

## Error decomposition

```{r}

uniformBias <- function(true, pred){
  n   <- length(true)
  out <- mean(pred - true)
  out <- (out**2)
  return(out)
}


consistencyBias <- function(true, pred, lm){
  b   <- lm$coefficients[[2]] # slope linear model
  out <- mean(true - mean(pred))
  out <- out*((b-1)**2)
  return(out)
}

```

```{r}
x  <- runif(1500,0,1)
y  <- .7*x + rnorm(1500,0.,.1)
getTheilCoefs(y,x)
```


